- hosts: webserver
  vars_prompt:
          - name: html_file
            private: no
            prompt: enter the file name
          - name: conten
            private: no
            prompt: enter the html file content


  vars_files:
          - "{{ansible_facts['distribution']}}-{{ansible_facts['distribution_major_version']}}.yml"
  tasks:
          - name: Install server
            package:
                    name: "{{ package_name }}"
                    state: present
          - name: Creating page
            copy:
                    content: "{{ conten }}"
                    dest: "{{doc_root}}/{{html_file}}.html"
          - name: Starting Service ...
            service:
                    name: "{{ service_name }}"
                    state: started
